vich_uploader:
  db_driver: orm

  metadata:
    type: annotation

  mappings:
    photo_user:
      uri_prefix: /images/userPics
      upload_destination: "%kernel.project_dir%/public/images/userPics"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
